"""add is_verified column to users

Revision ID: 8e02657bcf3f
Revises: 
Create Date: 2025-09-20 22:31:25.360314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e02657bcf3f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('contacts', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_contacts_id'), 'contacts', ['id'], unique=False)
    op.create_foreign_key(None, 'contacts', 'users', ['owner_id'], ['id'])
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=True))
    op.alter_column('contacts', 'owner_id', nullable=False)



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_verified')
    op.drop_constraint(None, 'contacts', type_='foreignkey')
    op.drop_index(op.f('ix_contacts_id'), table_name='contacts')
    op.drop_column('contacts', 'owner_id')
    # ### end Alembic commands ###
